### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by tonyteo-git** [Papooch/WasteOptimiser#24] opened 2022-12-13 01:26 UTC
Hi there @Papooch , long time no see, 
I try to test your Gcode you upload, it't work well, but i can't know my gcode error, can't you test it, thanks verry much
My data here [https://1drv.ms/u/s!AsM7aJ9xx4Mag_4MeulGhVLg5kUCnA?e=Q1muPG](url)

**Comment by Papooch** [comment] 2022-12-18 08:57
Hi, sorry, I only noticed the issue now. Since you closed it, have you solved it yourself, or do you want me to look into it?

**Comment by tonyteo-git** [comment] 2022-12-18 10:24
Oh, thank's very much, I think you are very busy, so I give up

**Comment by Papooch** [comment] 2022-12-18 16:17
So, I had a closer look, and while I couldn't find the cause, I found a way to make the gcodes at least readable. Frankly, the GCODE parser is very simple and I made it based on the GCODE output that the tool I used produced (and made some assumptions that are not generally true).

To make it work for your shapes:
 * remove the comment (it that breaks parsing if it's not on a separate line)
 * Duplicate the first G0 move and make it a G1 move
 * Add a G0 move at the very end of the shape

![image](https://user-images.githubusercontent.com/46406259/208308100-68c8dab6-0777-457c-82fc-26230ba7e66c.png)
![image](https://user-images.githubusercontent.com/46406259/208308357-c74e14d1-6072-419c-b60d-2f0fadc4f2dc.png)

You can also dig through the parser code as `parser/gcodeparser.py` and see if you can fix it. It's been a long time since I touched this and my career went a different direction.

**Closed as completed by Papooch** 2022-12-18 16:17 UTC
